### ISSUE TITLE
Demo for evaluating black-box attacks

### ISSUE THREAD

**Issue by HuangZuShu** [zhaoshiji123/MTARD#1]
Hi, thank you for sharing your code.
I found the code for evaluating is incomplete.
Would you mind committing code for evaluating black-box and white-box attack here?
Or send it to me via email: 2060271076@email.szu.edu.cn.
Thank you very much !

**Comment by zhaoshiji123** [comment]
您好！你的邮件已收到！祝顺利~zsj

**Comment by zhaoshiji123** [comment]
Hi, I have informed you by email.
Thanks for watching our work！

**Comment by HuangZuShu** [comment]
> Hi, I have informed you by email. Thanks for watching our work！

Thank you very much！
