### ISSUE TITLE
A question for nature teacher model.

### ISSUE THREAD

**Issue by Alienworm** [zhaoshiji123/MTARD#2]
Thank you for sharing your code. I wonder where the nature teacher model(RN-56) came from. Should  I retrain the model(RN-56).

**Comment by zhaoshiji123** [comment]
Hi! Original file of model come from https://github.com/chenyaofo/pytorch-cifar-models, we retrain it  For training details, please refer to our original training parameters for natural model) and finally obtain the performance claimed in our article.

**Comment by Alienworm** [comment]
> Hi! Original file of model come from https://github.com/chenyaofo/pytorch-cifar-models, we retrain it For training details, please refer to our original training parameters for natural model) and finally obtain the performance claimed in our article.

Thank you for your help!
