### ISSUE TITLE
About the natural teacher for CIFAR10

### ISSUE THREAD

**Issue by VincentZhou7** [zhaoshiji123/MTARD#5]
Hi. I am really interested to your team's work and is trying to replicate the result. When running the script for CIFAR10 dataset, I find that the checkpoint of natural teacher (Resnet56) you provided does not suit any resnet structure defined in your model part. I try to import the structure of resnet56 from other places but the checkpoint of natural teacher (Resnet56) still does not fit this structure.  Could you please provide the code of resnet56 structure def for the checkpoint of natural teacher for CIFAR10? 

Appreciate for your fantastic work and hope to get your response!

**Comment by zhaoshiji123** [comment]
Hi! The resnet structure has been updated!

**Comment by VincentZhou7** [comment]
The updated structure works fine. Thank you!
