### ISSUE TITLE
About black-box evaluation

### ISSUE THREAD

**Issue by XingweiDeng** [zhaoshiji123/MTARD#6]
Hi, thank you for sharing your code. I found the code for evaluating is incomplete. Can you tell me where the implementation of black-box testing is？

**Comment by XingweiDeng** [comment]
I hope you can reply to me. Thank you.

**Comment by zhaoshiji123** [comment]
The evaluation code of black attack (including PGD and CW) is based on 
 [ZFancy/IAD: [ICLR 2022] Reliable Adversarial Distillation with Unreliable Teachers (github.com)](https://github.com/ZFancy/IAD)

Meanwhile, the square attack is evaluated based on the the part of autoattack.

**Comment by XingweiDeng** [comment]
Thank you so much！！！
